### ISSUE TITLE
[UseDotNet] Can't use previous dotnet version when later version is installed

### ISSUE THREAD

**Issue by dnperfors** [microsoft/azure-pipelines-tasks#12609]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UseDotNet

## Environment
- Server - Azure DevOps Server (on-premise) 2019 version: Dev17.M153.1
- Agent - Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
      OS: Ubuntu 18.04
      Agent version: 2.164.0

## Issue Description
In my pipeline I use the `UseDotNet` task to install dotnet core sdk. After installing version 3.1.200 we found some issues, so we wanted to revert back to 3.1.101. However when running the pipeline again, version 3.1.200 is still being used.

Relevant part of the pipeline:
```
steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.101'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: '--version'
```

Expected output of `DotNetCoreCLI` task: 3.1.101
Actual output of `DotNetCoreCLI` task: 3.1.200

### Task logs

Debug output from UseDotNet tasks:
```
##[debug]Evaluating condition for step: 'UseDotNet'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
##[section]Starting: UseDotNet
==============================================================================
Task         : Use dotnet
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.0.5
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
##[debug]agent.TempDirectory=/workspace/_temp
##[debug]loading inputs and endpoints
##[debug]loading INPUT_PACKAGETYPE
##[debug]loading INPUT_VERSION
##[debug]loading INPUT_INCLUDEPREVIEWVERSIONS
##[debug]loading INPUT_INSTALLATIONPATH
##[debug]loading INPUT_PERFORMMULTILEVELLOOKUP
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loading SECRET_SPECSYNCPATTOKEN
##[debug]loaded 10
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]check path : /workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/node_modules/azure-pipelines-tool-lib/lib.json
##[debug]adding resource file: /workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/node_modules/azure-pipelines-tool-lib/lib.json
##[debug]system.culture=en-US
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]check path : /workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/node_modules/packaging-common/node_modules/azure-pipelines-tool-lib/lib.json
##[debug]adding resource file: /workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/node_modules/packaging-common/node_modules/azure-pipelines-tool-lib/lib.json
##[debug]system.culture=en-US
##[debug]Setting resource path to /workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/task.json
##[debug]check path : /workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/task.json
##[debug]adding resource file: /workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/task.json
##[debug]system.culture=en-US
##[debug]check path : /workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/node_modules/packaging-common/module.json
##[debug]adding resource file: /workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/node_modules/packaging-common/module.json
##[debug]system.culture=en-US
##[debug]packageType=sdk
##[debug]version=3.1.101
Tool to install: .NET Core sdk version 3.1.101.
##[debug]installationPath=/workspace/_tool/dotnet
##[debug]includePreviewVersions=false
##[debug]agent.proxyurl=undefined
##[debug]AZURE_HTTP_USER_AGENT=TFS_6179c51a-69b7-40d9-a6f6-5caceb310a66_build_441_0
##[debug]Finding channel 3.1 for version 3.1.101
##[debug]In release undefined for version 3.1.100, File data is incorrect (might have missing required fields, such as name, rid and url): Version's files data is missing or has missing required fields.
##[debug]In release undefined for version 3.1.100, File data is incorrect (might have missing required fields, such as name, rid and url): Version's files data is missing or has missing required fields.
##[debug]In release undefined for version 3.1.100-preview3-014645, File data is incorrect (might have missing required fields, such as name, rid and url): Version's files data is missing or has missing required fields.
##[debug]In release undefined for version 3.1.100-preview3-014645, File data is incorrect (might have missing required fields, such as name, rid and url): Version's files data is missing or has missing required fields.
##[debug]In release undefined for version 3.1.100-preview2-014569, File data is incorrect (might have missing required fields, such as name, rid and url): Version's files data is missing or has missing required fields.
##[debug]In release undefined for version 3.1.100-preview2-014569, File data is incorrect (might have missing required fields, such as name, rid and url): Version's files data is missing or has missing required fields.
##[debug]In release undefined for version 3.1.100-preview1-014459, File data is incorrect (might have missing required fields, such as name, rid and url): Version's files data is missing or has missing required fields.
##[debug]In release undefined for version 3.1.100-preview1-014459, File data is incorrect (might have missing required fields, such as name, rid and url): Version's files data is missing or has missing required fields.
Found version 3.1.101 in channel 3.1 for user specified version spec: 3.1.101
##[debug]Processed: ##vso[telemetry.publish area=TaskDeploymentMethod;feature=UseDotNetV2]{"userVersion":"3.1.101", "resolvedVersion":"3.1.101"}
##[debug]isExplicit: 3.1.101
##[debug]explicit? true
Version 3.1.101 was not found in cache.
Getting URL to download .NET Core sdk version: 3.1.101.
Detecting OS platform to find correct download package for the OS.
##[debug]which '/workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/externals/get-os-distro.sh'
##[debug]found: '/workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/externals/get-os-distro.sh'
##[debug]which '/workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/externals/get-os-distro.sh'
##[debug]found: '/workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/externals/get-os-distro.sh'
##[debug]which '/workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/externals/get-os-distro.sh'
##[debug]found: '/workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/externals/get-os-distro.sh'
##[debug]which '/workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/externals/get-os-distro.sh'
##[debug]found: '/workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/externals/get-os-distro.sh'
##[debug]exec tool: /workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/externals/get-os-distro.sh
##[debug]arguments:
[command]/workspace/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.0.5/externals/get-os-distro.sh
Primary:linux-x64
Legacy:ubuntu.18.04-x64
Detected platform (Primary): linux-x64
Detected platform (Legacy): ubuntu.18.04-x64
##[debug]Got download URL for platform with rid: linux-x64
##[debug]
##[debug]Agent.Version=2.164.0
##[debug]Agent.TempDirectory=/workspace/_temp
##[debug]testing directory '/workspace/_temp'
Downloading: https://download.visualstudio.microsoft.com/download/pr/c4b503d6-2f41-4908-b634-270a0a1dcfca/c5a20e42868a48a2cd1ae27cf038044c/dotnet-sdk-3.1.101-linux-x64.tar.gz
##[debug]destination /workspace/_temp/9acab4c3-9d91-4f95-853a-fcce960ee57a
##[debug]downloading
##[debug]creating stream
##[debug]download complete
Extracting downloaded package /workspace/_temp/9acab4c3-9d91-4f95-853a-fcce960ee57a.
Extracting archive
##[debug]Agent.Version=2.164.0
##[debug]Agent.TempDirectory=/workspace/_temp
##[debug]testing directory '/workspace/_temp/ba6cc3b1-fbb9-4bc4-9841-20c98ef1b191'
##[debug]testing directory '/workspace/_temp'
##[debug]mkdir '/workspace/_temp/ba6cc3b1-fbb9-4bc4-9841-20c98ef1b191'
##[debug]which 'tar'
##[debug]found: '/bin/tar'
##[debug]which 'tar'
##[debug]found: '/bin/tar'
##[debug]/bin/tar arg: ["xzC","/workspace/_temp/ba6cc3b1-fbb9-4bc4-9841-20c98ef1b191","-f","/workspace/_temp/9acab4c3-9d91-4f95-853a-fcce960ee57a"]
##[debug]exec tool: /bin/tar
##[debug]arguments:
##[debug]   xzC
##[debug]   /workspace/_temp/ba6cc3b1-fbb9-4bc4-9841-20c98ef1b191
##[debug]   -f
##[debug]   /workspace/_temp/9acab4c3-9d91-4f95-853a-fcce960ee57a
[command]/bin/tar xzC /workspace/_temp/ba6cc3b1-fbb9-4bc4-9841-20c98ef1b191 -f /workspace/_temp/9acab4c3-9d91-4f95-853a-fcce960ee57a
##[debug]Exit code 0 received from tool '/bin/tar'
##[debug]STDIO streams have closed for tool '/bin/tar'
##[debug]Copying all root folders into installation path: /workspace/_tool/dotnet
##[debug]Comparing if version being installed 3.1.101 is greater than already installed version with folder name 3.1.101
##[debug]isExplicit: 3.1.101
##[debug]explicit? true
##[debug]isExplicit: 3.1.101
##[debug]explicit? true
##[debug]Comparing if version being installed 3.1.101 is greater than already installed version with folder name 3.1.102
##[debug]isExplicit: 3.1.102
##[debug]explicit? true
##[debug]isExplicit: 3.1.101
##[debug]explicit? true
##[debug]Version: 3.1.101 is not the latest among the versions present at /workspace/_tool/dotnet
##[debug]Creating installation complete file for .Net core 3.1.101 version sdk
Successfully installed .NET Core sdk version 3.1.101.
##[debug]Agent.Version=2.164.0
##[debug]Processed: ##vso[task.prependpath]/workspace/_tool/dotnet
##[debug]set DOTNET_ROOT=/workspace/_tool/dotnet
##[debug]Processed: ##vso[task.setvariable variable=DOTNET_ROOT;issecret=false;]/workspace/_tool/dotnet
##[debug]performMultiLevelLookup=false
##[debug]set DOTNET_MULTILEVEL_LOOKUP=0
##[debug]Processed: ##vso[task.setvariable variable=DOTNET_MULTILEVEL_LOOKUP;issecret=false;]0
##[debug]nugetVersion=undefined
##[debug]Agent.ProxyUrl=undefined
Creating global tool path and pre-pending to PATH.
##[debug]testing directory '/root/.dotnet/tools'
##[debug]Agent.Version=2.164.0
##[debug]Processed: ##vso[task.prependpath]/root/.dotnet/tools
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]
##[section]Finishing: UseDotNet
```
Debug output from `DotNetCoreCLI` tasks:
```
##[debug]Evaluating condition for step: 'DotNetCoreCLI'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
##[section]Starting: DotNetCoreCLI
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.153.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
##[debug]agent.TempDirectory=/workspace/_temp
##[debug]loading inputs and endpoints
##[debug]loading INPUT_COMMAND
##[debug]loading INPUT_PUBLISHWEBPROJECTS
##[debug]loading INPUT_CUSTOM
##[debug]loading INPUT_PUBLISHTESTRESULTS
##[debug]loading INPUT_ZIPAFTERPUBLISH
##[debug]loading INPUT_MODIFYOUTPUTPATH
##[debug]loading INPUT_SELECTORCONFIG
##[debug]loading INPUT_INCLUDENUGETORG
##[debug]loading INPUT_NUGETCONFIGPATH
##[debug]loading INPUT_NOCACHE
##[debug]loading INPUT_VERBOSITYRESTORE
##[debug]loading INPUT_SEARCHPATTERNPUSH
##[debug]loading INPUT_NUGETFEEDTYPE
##[debug]loading INPUT_PUBLISHPACKAGEMETADATA
##[debug]loading INPUT_SEARCHPATTERNPACK
##[debug]loading INPUT_CONFIGURATIONTOPACK
##[debug]loading INPUT_OUTPUTDIR
##[debug]loading INPUT_NOBUILD
##[debug]loading INPUT_INCLUDESYMBOLS
##[debug]loading INPUT_INCLUDESOURCE
##[debug]loading INPUT_VERSIONINGSCHEME
##[debug]loading INPUT_REQUESTEDMAJORVERSION
##[debug]loading INPUT_REQUESTEDMINORVERSION
##[debug]loading INPUT_REQUESTEDPATCHVERSION
##[debug]loading INPUT_VERBOSITYPACK
##[debug]loading INPUT_WORKINGDIRECTORY
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loading SECRET_SPECSYNCPATTOKEN
##[debug]loaded 31
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]command=custom
##[debug]projects=null
##[debug]arguments=null
##[debug]publishWebProjects=true
##[debug]zipAfterPublish=true
##[debug]workingDirectory=/workspace/8/s
##[debug]check path : /workspace/_tasks/DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b/2.153.0/task.json
##[debug]adding resource file: /workspace/_tasks/DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b/2.153.0/task.json
##[debug]system.culture=en-US
##[debug]custom=--version
##[debug]which 'dotnet'
##[debug]found: '/workspace/_tool/dotnet/dotnet'
##[debug]which 'dotnet'
##[debug]found: '/workspace/_tool/dotnet/dotnet'
##[debug]which '/workspace/_tool/dotnet/dotnet'
##[debug]found: '/workspace/_tool/dotnet/dotnet'
##[debug]which '/workspace/_tool/dotnet/dotnet'
##[debug]found: '/workspace/_tool/dotnet/dotnet'
##[debug]/workspace/_tool/dotnet/dotnet arg: --version
##[debug]exec tool: /workspace/_tool/dotnet/dotnet
##[debug]arguments:
##[debug]   --version
[command]/workspace/_tool/dotnet/dotnet --version
3.1.200
##[debug]Exit code 0 received from tool '/workspace/_tool/dotnet/dotnet'
##[debug]STDIO streams have closed for tool '/workspace/_tool/dotnet/dotnet'
##[section]Finishing: DotNetCoreCLI
```

**Comment by dnperfors** [comment]
Could using a global.json be a workaround here?

**Comment by vineetmimrot** [comment]
I think this is happening because of this functionality

https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/multilevel-sharedfx-lookup.md#framework-search
> For releases:
Search for the version specified. If it cannot be found, roll-forward to the closest version (behavior is configurable).
Once a version has been selected, roll-forward to the latest patch version (this functionality is enabled by default, but can be turned off).

**Comment by vineetmimrot** [comment]
You should use global.json to use lower version then installed.
https://docs.microsoft.com/en-us/dotnet/core/versions/selection#the-sdk-uses-the-latest-installed-version

> On rare occasions, you may need to use an earlier version of the SDK. You specify that version in a global.json file. The "use latest" policy means you only use global.json to specify a .NET Core SDK version earlier than the latest installed version.

**Comment by anuragc617** [comment]
@dnperfors  have you tried the workaround suggested above?

**Comment by dnperfors** [comment]
Yes, using the global.json does work for the build server. However it is not practical, since locally you also need to have the exact same version of the sdk, which adds an extra step when you relly on Visual Studio to install the SDK

**Comment by bishal-pdMSFT** [comment]
@dnperfors this is an intended behavior of the task. Depending on where you are asking the task (or using default value) it will re-use previously installed .NET core SDK. Look at `installationPath` input in the [doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops#task-inputs)
You have two options:
1. Use global.json as suggested earlier. In your case when a [latest SDK](https://docs.microsoft.com/en-us/dotnet/core/versions/selection#the-sdk-uses-the-latest-installed-version) does not work as intended, I think it is a fit case of using global.json.
2. Another option is to specify a non-default value for `installationPath` input. You can use `$(Agent.TempDirectory)` or any other temp directory. Please note that this means that SDK will be re-installed every time.

**Comment by vinodkumar3** [comment]
@dnperfors 
Hope workarounds suggested by Bishal working fine for you. If you have any queries/concerns, please let us know.

**Comment by dnperfors** [comment]
I didn’t test that work around. In the meantime the reason for using an older version of the SDKs was resolved. But I will keep this information in mind. Thanks for the clarification.

**Comment by vinodkumar3** [comment]
Sure. Feel free to reopen the issue if you face the issue again or have any more queries related to the issue.

**Comment by matthoulb** [comment]
Why has this been closed? 

The "Use .NET Core" task specifically states:
"Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. **Use this task to change the version of .NET Core used in subsequent tasks**. Additionally provides proxy support."

The actual functionality appears not to be this at all?  It appears to install the requested version, but actually use the latest version that's installed.  Clearly that is not correct.

Using a global.json is a nasty workaround to a problem that doesn't need to exist.

**Comment by BassaForte** [comment]
It seems the "Use .NET Core" task does not work at all. I added the task at the beginning of my pipeline to use dotnet core 3.1.403; the task passes, but it runs the following dotnet cli tasks with version 2.177.1. The weird thing is, my pipeline was working fine 3 days ago with no changes to dotnet version ¯\_(ツ)_/¯

**Comment by bishal-pdMSFT** [comment]
@BassaForte @matthoulb this is a closed issue with [details ](https://github.com/microsoft/azure-pipelines-tasks/issues/12609#issuecomment-611728794)provided.

If you feel that such behavior is not good, please open a new issue and share more details/thoughts there.

**Comment by BassaForte** [comment]
> 
> 
> @BassaForte @matthoulb this is a closed issue with [details ](https://github.com/microsoft/azure-pipelines-tasks/issues/12609#issuecomment-611728794)provided.
> 
> If you feel that such behavior is not good, please open a new issue and share more details/thoughts there.

Sorry, I should have included some vital information in my comment. I tried the global.json workaround, that also didn't work. My agent refuses to use any dotnet core version other than 2.177.1. I felt my issue was directly associated with this issue, and that's why I commented. People are obviously still having issues with the dotnet cli task, directly related to this issue, so maybe it should have been closed?

**Comment by bishal-pdMSFT** [comment]
Can you please share the pipeline yaml/json to understand better of how you are using the tasks. Also, specify whether you are using hosted or private agent.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BassaForte** [comment]
> 
> Can you please share the pipeline yaml/json to understand better of how you are using the tasks. Also, specify whether you are using hosted or private agent. Get Outlook for Android<https://aka.ms/ghei36>
> […](#)
> ________________________________ From: Chris <notifications@github.com> Sent: Tuesday, November 24, 2020 5:59:56 PM To: microsoft/azure-pipelines-tasks <azure-pipelines-tasks@noreply.github.com> Cc: Bishal Prasad <biprasad@microsoft.com>; Assign <assign@noreply.github.com> Subject: Re: [microsoft/azure-pipelines-tasks] [UseDotNet] Can't use previous dotnet version when later version is installed (#12609) @BassaForte<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBassaForte&data=04%7C01%7Cbiprasad%40microsoft.com%7C4033ed924a214738442308d89074a70f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637418177995618731%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sd%2FDbZCuwGKNYayFP3JLvRSwHu4xzeEJXmW3y0Q1Hb4%3D&reserved=0> @matthoulb<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmatthoulb&data=04%7C01%7Cbiprasad%40microsoft.com%7C4033ed924a214738442308d89074a70f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637418177995628732%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mUZWWsdb84zYf0zgFR0O8t1RWaz7EFTqrb4R3NzQ4x4%3D&reserved=0> this is a closed issue with details <https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fazure-pipelines-tasks%2Fissues%2F12609%23issuecomment-611728794&data=04%7C01%7Cbiprasad%40microsoft.com%7C4033ed924a214738442308d89074a70f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637418177995628732%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y6GBHZGxHBee7Jj1l3cPg4p3IWAiLshl1M7ampz7rWc%3D&reserved=0> provided. If you feel that such behavior is not good, please open a new issue and share more details/thoughts there. Sorry, I should have included some vital information in my comment. I tried the global.json workaround, that also didn't work. My agent refuses to use any dotnet core version other than 2.177.1. I felt my issue was directly associated with this issue, and that's why I commented. People are obviously still having issues with the dotnet cli task, directly related to this issue, so maybe it should have been closed? — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fazure-pipelines-tasks%2Fissues%2F12609%23issuecomment-732943992&data=04%7C01%7Cbiprasad%40microsoft.com%7C4033ed924a214738442308d89074a70f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637418177995638718%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Aia%2Fmy%2B6r9NwJodJIGs6F8wWY9hOkxRkDHcthmGRfKg%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB3XU7LBGQ5PWM6BGMHFSUDSRORMJANCNFSM4LYW6JDQ&data=04%7C01%7Cbiprasad%40microsoft.com%7C4033ed924a214738442308d89074a70f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637418177995638718%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BNXBeBypyw8fyIXvolu4CxI5ouBUN7jhzbDZpdQE%2F1k%3D&reserved=0>.

This is my yaml. It's running on a private agent, and the step that is failing due to wrong .net core version is "Build Server".

`trigger:
- master

stages:
- stage: BuildAll
  jobs:
  - job: BuildAndroid
    steps:
    
    # Checkout (LFS)
    - script: git clean -ffdx -e "*/[Ll]ibrary/" -e "*/[Pp]ackages/" -e "*.sln" -e "*.csproj"
      displayName: 'Clean'
      condition: false
      continueOnError: true
    - checkout: self
      clean: false
      lfs: true
  
    # Build Game
    - task: UnityBuildTask@3
      displayName: 'Build Project (Android)'
      inputs:
        buildTarget: Android
        unityEditorsPathMode: 'specify'
        customUnityEditorsPath: '$(UnityPath)'
        unityProjectPath: '$(ProjectPath)'
        buildScriptType: 'existing'
        scriptExecuteMethod: 'Build.BuildTools.RunAutomatedAndroidBuild'
        additionalCmdArgs: '-logfile - -outputPath $(OutputPath) -outputFileName Avalice'
    
    # Use dotnet core 3.1.403
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.1.403'

    # Build Server
    - task: DotNetCoreCLI@2
      displayName: 'Build Server'
      inputs:
        command: 'build'
        projects: '$(ServerPath)/AvaliceServer.sln'
        arguments: '--configuration release'

    # Run tests
    - script: '"$(UnityPath)\$(ProjectVersion)\Editor\Unity.exe" -batchmode -projectPath $(ProjectPathFull) -logfile - -nographics -runTests -testPlatform editmode -testResults $(OutputPath)\TEST-EditMode.xml'
      displayName: 'Run Edit Mode Tests'
      continueOnError: true
    - script: '"$(UnityPath)\$(ProjectVersion)\Editor\Unity.exe" -batchmode -projectPath $(ProjectPathFull) -logfile - -nographics -runTests -testPlatform playmode -testResults $(OutputPath)\TEST-PlayMode.xml'
      displayName: 'Run Play Mode Tests'
      continueOnError: true
    - task: DotNetCoreCLI@2
      displayName: 'Run Server Tests'
      inputs:
        command: 'test'
        projects: '$(ServerPath)/AvaliceServer.sln'

    # Publish
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: '**/TEST-*.xml'
        searchFolder: '$(OutputPath)'
        failTaskOnFailedTests: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(OutputPath)'
        ArtifactName: 'Avalice-$(Build.BuildNumber)'
        publishLocation: 'Container'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(ServerBin)'
        ArtifactName: 'Avalice-$(Build.BuildNumber)'
        publishLocation: 'Container'
`

**Comment by bishal-pdMSFT** [comment]
The yaml looks pretty straightforward. Could you please share the build logs to check any anomaly there?

**Comment by BassaForte** [comment]
Sure thing, here are the log files for those two steps (UseDotNet and Build Server).

[4_Install .NET Core 3.1 SDK.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5598724/4_Install.NET.Core.3.1.SDK.txt)
[6_Build Server.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5598732/6_Build.Server.txt)

**Comment by bishal-pdMSFT** [comment]
@BassaForte I am sure why you think dotnet version being used is not 3.1.403. I think you might have perceived the task version (wchich is actually 2.177) to be .Net Core version.
I would request two things:
1. Set debug flags and collect the build logs again. This will print more information which would be helpful.
2. Add one more step immeditely after `UseDotNet` step to run a simple shell command `dotnet --info`

**Comment by BassaForte** [comment]
@bishal-pdMSFT You're right, I was confused about that task version, I had thought it was the dotnet core version. I ran the build again with debug flags (I assume you meant changing the configuration from release to debug) and running `dotnet --info` right after. Here are the build logs:

[6_CmdLine.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5599129/6_CmdLine.txt)
[7_Build Server.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5599130/7_Build.Server.txt)

Also, if it's not dotnet core, I'm really not sure what's causing the restore to fail. The Nuget version looked right to me, and I tried adding a Nuget restore task before the UseDotNet, but that didn't seem to help either (even though that task passed). I really appreciate your help, by the way.

**Comment by bishal-pdMSFT** [comment]
IMO some settings might be missing from csproj. Are you able to build this project using similar steps manually on your dev box?

I would suggest you to create issue in dotnet repo and get their help about this build error

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BassaForte** [comment]
> 
> IMO some settings might be missing from csproj. Are you able to build this project using similar steps manually on your dev box? I would suggest you to create issue in dotnet repo and get their help about this build error Get Outlook for Android<https://aka.ms/ghei36>

It doesn't look like there are any settings missing from the csproj, but perhaps you're right. I am able to build this project using dotnet build both on my dev machine, as well as on the agent machine (although again I understand the agent runs on a different environment).

Now that I understand that it's not the UseDotNet command, I'll seek help elsewhere. Thanks again for your assistance, and hopefully the other people having the issue will gain something from this as well.

**Comment by Berthelmaster** [comment]
Anything new about this issue? 

We're experiencing this issue after a project installed Dotnet 8 rc-2 and the other projects (running on the same Agent) fails, because they are switched to Dotnet 8, even though we specify Dotnet 6 in the yaml file. :/

**Comment by Devqon** [comment]
Any news on this? We have the same behavior as described here; We have a new project which uses .NET8-rc2, but using the same (self-hosted) agents for our 'older' projects which use .NET6 now fail because of that.

As a workaround we now have a dedicated Agent (+ pool) for .NET 8 projects, but this behavior is very confusing.

**Comment by madibaT** [comment]
I think this task should be re-opened. We're seeing the same behaviour as well. @vinodkumar3

**Comment by MartinDemberger** [comment]
It's working with verison 8.0.101 which

```yaml
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 8.x'
  inputs:
    packageType: 'sdk'
    version: '8.0.101'
    includePreviewVersions: true
    performMultiLevelLookup: true
```

**Comment by antmeehan** [comment]
I just got burnt again by this behaviour.  Here is the task:

```yaml
- task: UseDotNet@2
  inputs:
    version: 8.0.100
```

Looks like it has worked as promised.

```
Tool to install: .NET Core sdk version 8.0.100.
Found version 8.0.100 in channel 8.0 for user specified version spec: 8.0.100
Version: 8.0.100 was found in cache.
Creating global tool path and pre-pending to PATH.
```

But you get burnt later with the latest cached version actually being used 😢 

```
 CSC : error CS9057: The analyzer assembly 'C:\agent\_work\_tool\dotnet\sdk\8.0.201\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.CodeAnalysis.Razor.Compiler.SourceGenerators.dll' references version '4.9.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. 
```
(Spot the `8.0.201`)

**Comment by mikeobrien** [comment]
Same here:

```
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.203'
```

```
Tool to install: .NET Core sdk version 9.0.203.
Found version 9.0.203 in channel 9.0 for user specified version spec: 9.0.203
Version: 9.0.203 was found in cache.
Creating global tool path and pre-pending to PATH.
```

```
- task: DotNetCoreCLI@2
  displayName: '.NET Core Info'
  inputs:
    command: 'custom'
    custom: '--info'
```

```
.NET SDK:
 Version:           9.0.300
 Commit:            15606fe0a8
 Workload version:  9.0.300-manifests.c678e91b
 MSBuild version:   17.14.5+edd3bbf37
```
