### ISSUE TITLE
[REGRESSION]: AzureFunctionApp@2 v2.273.0 — archiver 7.0 upgrade stores symlinks as plain files in deployment zip

### ISSUE THREAD

**Issue by yodelzach** [microsoft/azure-pipelines-tasks#22154]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureFunctionApp

### Breaking task version

2.273.0

### Last working task version

2.272.0

### Regression Description

AzureFunctionApp@2 v2.273.0 stores Unix symlinks as plain files (containing the target 
path as text) in the deployment zip, instead of following them and including the actual 
file contents. This causes complete outages for Node.js Function Apps that use local 
module references ("file:./my-local-module" in package.json), which npm resolves as 
symlinks in node_modules/.

After upgrading from v2.272.0 to v2.273.0, node_modules/my-local-module (a symlink to 
../my-local-module) is stored in the deployment zip as a 9-byte file containing the text 
"../my-local-module" instead of the actual directory contents. On the Windows Function 
App host, this results in:

  Cannot find module 'my-local-module/some-file.js'

Every function in the app fails. The same code deployed via `func azure functionapp 
publish` (Azure Functions Core Tools) works fine.

The root cause is PR #22096 ("Fix CVE-2026-41672"), which ran `npm audit fix` and 
cascaded into a major transitive dependency bump:

  azure-pipelines-tasks-webdeployment-common: 4.272.1 → 4.274.0
    └── archiver: 5.x → 7.0.1  (MAJOR version bump)
          └── archiver-utils: 4.x → 5.0.2

archiver 7.0 changed directory traversal from fs.stat() (follows symlinks transparently) 
to fs.lstat() (preserves symlinks as-is). The archiver does not set dereference: true, 
so symlinks are stored verbatim in the zip.

Expected: Symlinks in node_modules/ are followed and their contents included in the 
deployment zip (as in v2.272.0).

Actual: Symlinks are stored as small files whose content is the target path string.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04 (build agent) → Windows (Function App host)

### Relevant log output

```shell
Exception: Worker was unable to load function myFunction_http: 
'Cannot find module 'my-local-module/core/SomeManager.js'
Require stack:
- C:\home\site\wwwroot\core\SomeManager.js
- C:\home\site\wwwroot\myFunction_http\index.js
- C:\Program Files (x86)\SiteExtensions\Functions\4.1048.200\workers\node\dist\src\worker-bundle.js'
```

### Full task logs with system.debug enabled

<details>
  <summary>UNSUCCESSFUL RUN</summary>
  <pre>
  Task: AzureFunctionApp 2.273.0
  Kudu inspection of deployed artifact:
  > dir node_modules\my-local-module
  05/07/2026  02:14 AM                 9 my-local-module    ← 9-byte file, NOT a directory
  
  > type node_modules\my-local-module
  ../my-local-module                                        ← symlink target stored as file content
  </pre>
</details>

<details>
  <summary>SUCCESSFUL RUN</summary>
  <pre>
  Task: AzureFunctionApp 2.272.0
  Kudu inspection of deployed artifact:
  > dir node_modules\my-local-module
  05/06/2026  11:30 PM    <DIR>          .
  05/06/2026  11:30 PM    <DIR>          ..
  05/06/2026  11:30 PM    <DIR>          src        ← real directory with actual files
  05/06/2026  11:30 PM    <DIR>          lib
  05/06/2026  11:30 PM    <DIR>          utils
  </pre>
</details>

### Repro steps

```yml
# 1. Create a Node.js Function App with a local module dependency:
#    package.json: { "dependencies": { "my-local-module": "file:./my-local-module" } }
#    This causes npm install to create: node_modules/my-local-module → ../my-local-module (symlink)
#
# 2. Deploy using AzureFunctionApp@2 task v2.273.0
#
# 3. Observe: node_modules/my-local-module on the Function App is a 9-byte file 
#    containing "../my-local-module" instead of the actual directory contents
#
# Minimal pipeline YAML to reproduce:

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'

  - script: |
      npm install
      npm run build --if-present
    displayName: 'Build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: '7z'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).7z'

  # Deploy using AzureFunctionApp@2 — this re-zips with archiver 7.0
  # which stores the node_modules/my-local-module symlink as a plain file
  - task: AzureFunctionApp@2
    inputs:
      azureSubscription: '<subscription>'
      appType: 'functionApp'
      appName: '<function-app-name>'
      package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).7z'
```

**Comment by v-abhishera** [comment]
@yodelzach Can you share the full detailed logs of the successful and failed pipelines with error message by adding

"system.debug=true" as pipeline variables

**Comment by yodelzach** [comment]
@v-abhishera I have since updated my build pipeline to work around this issue, so I cannot run the pipeline again with the system.debug variable to see the failed state.

I have this log from the run that presented with the issue

2026-05-07T12:32:19.7999656Z ##[section]Starting: Azure Function App Deploy: <FUNCTION_APP_NAME>
2026-05-07T12:32:19.8008637Z ==============================================================================
2026-05-07T12:32:19.8008753Z Task         : Azure Functions Deploy
2026-05-07T12:32:19.8008820Z Description  : Update a function app with .NET, Python, JavaScript, PowerShell, Java based web applications
2026-05-07T12:32:19.8008930Z Version      : 2.273.0
2026-05-07T12:32:19.8008994Z Author       : Microsoft Corporation
2026-05-07T12:32:19.8009066Z Help         : https://aka.ms/azurefunctiontroubleshooting
2026-05-07T12:32:19.8009140Z ==============================================================================
2026-05-07T12:32:20.5095338Z Got service connection details for Azure App Service:'<FUNCTION_APP_NAME>'
2026-05-07T12:32:58.6329897Z Updating App Service Application settings. Data: {"WEBSITE_RUN_FROM_PACKAGE":"1"}
2026-05-07T12:32:58.6331976Z App Service Application settings are already present.
2026-05-07T12:33:03.1177987Z Validating deployment package for functions app before Zip Deploy
2026-05-07T12:33:04.6506971Z Package deployment using ZIP Deploy initiated.
2026-05-07T12:33:21.0094251Z Deploy logs can be viewed at https://<FUNCTION_APP_NAME>.scm.azurewebsites.net/api/deployments/<DEPLOYMENT_ID>/log
2026-05-07T12:33:21.0096353Z The web package has been deployed to App Service. Please note that the package mount or extraction errors will be logged in the deployment logs in the location above.
2026-05-07T12:33:21.0096839Z NOTE: Run From Package makes wwwroot read-only, so you will receive an error when writing files to this directory.
2026-05-07T12:33:24.5780412Z Successfully added release annotation to the Application Insight : <APP_INSIGHTS_NAME>
2026-05-07T12:33:24.9632976Z App Service Application URL: https://<FUNCTION_APP_NAME>.azurewebsites.net
2026-05-07T12:33:25.0230260Z ##[section]Finishing: Azure Function App Deploy: <FUNCTION_APP_NAME>

Successful run on previous version looks pretty much identical
2026-05-06T16:54:59.6818347Z ##[section]Starting: Azure Function App Deploy: <FUNCTION_APP_NAME>
2026-05-06T16:54:59.6824826Z ==============================================================================
2026-05-06T16:54:59.6824939Z Task         : Azure Functions Deploy
2026-05-06T16:54:59.6825009Z Description  : Update a function app with .NET, Python, JavaScript, PowerShell, Java based web applications
2026-05-06T16:54:59.6825444Z Version      : 2.272.0
2026-05-06T16:54:59.6825513Z Author       : Microsoft Corporation
2026-05-06T16:54:59.6825593Z Help         : https://aka.ms/azurefunctiontroubleshooting
2026-05-06T16:54:59.6825667Z ==============================================================================
2026-05-06T16:55:00.3585325Z Got service connection details for Azure App Service:'<FUNCTION_APP_NAME>'
2026-05-06T16:55:55.2557413Z Updating App Service Application settings. Data: {"WEBSITE_RUN_FROM_PACKAGE":"1"}
2026-05-06T16:55:55.2560238Z App Service Application settings are already present.
2026-05-06T16:55:59.5390536Z Validating deployment package for functions app before Zip Deploy
2026-05-06T16:56:01.3136936Z Package deployment using ZIP Deploy initiated.
2026-05-06T16:56:18.1344191Z Deploy logs can be viewed at https://<FUNCTION_APP_NAME>.scm.azurewebsites.net/api/deployments/<DEPLOYMENT_ID>/log
2026-05-06T16:56:18.1345728Z The web package has been deployed to App Service. Please note that the package mount or extraction errors will be logged in the deployment logs in the location above.
2026-05-06T16:56:18.1352538Z NOTE: Run From Package makes wwwroot read-only, so you will receive an error when writing files to this directory.
2026-05-06T16:56:19.7304446Z Successfully added release annotation to the Application Insight : <APP_INSIGHTS_NAME>
2026-05-06T16:56:20.3196210Z App Service Application URL: https://<FUNCTION_APP_NAME>.azurewebsites.net
2026-05-06T16:56:20.3940335Z ##[section]Finishing: Azure Function App Deploy: <FUNCTION_APP_NAME>

**Comment by v-abhishera** [comment]
@yodelzach We have currently overridden the task to use the stable version while we investigate the issue and work on a fix. If you rerun the pipeline, it will now use the stable version.

Could you please share the workaround you used to address the issue?

**Comment by v-abhishera** [comment]
@yodelzach Can we have some updates on this issue?

**Comment by v-abhishera** [comment]
@yodelzach Can we have some updates on this issue?

**Comment by v-abhishera** [comment]
@yodelzach Can we have some updates on this issue?
