### ISSUE TITLE
docker builAndPush task failed after upgrade agent to 2.174.1

### ISSUE THREAD

**Issue by mchenx** [microsoft/azure-pipelines-tasks#13541]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: docker buildAndPush  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - VSTS on-premises?
    
    - If using TFS on-premises, provide the version: 2.174.1
    

- Agent - Hosted or Private:  private
    
    - If using private agent, provide the OS of the machine running the agent and the agent version:  CentOS 7.6

- .Net Core Runtime 2.1.11

## Issue Description

Everything was fine when running with vsts agent 2.153.0, but got "##[error]TypeError: _crypto.default.randomFillSync is not a function" error after upgraded to 2.160.0, according to [https://developercommunity.visualstudio.com/content/problem/1148859/-cryptodefaultrandomfillsync-is-not-a-function-whe.html](url) I upgraded the vsts agent to 2.174.1. Duing the configuration of vsts agent 2.174.1 I got "couldn't find a valid ICU package on the system." error, according to some of the microsoft docs, I set "configProperties": { "System.Globalization.Invariant": true } in the bin/Agent.Listener.runtimeconfig.json under the vsts folder and got the new vsts version installed and configured successfully. But when running a previoous build pipeline which includes docker buildAndPush task, it failed.

But I am able to run 'docker build' directly on the build server.

I read some threads which said the issue was related to centos6, but it is centos7 in my case, and my vsts agent was working fine before.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

![image](https://user-images.githubusercontent.com/1550186/93038377-612b7300-f677-11ea-8844-59aaa0a56a55.png)

**Comment by ds-ms** [comment]
This seems like an issue related to the agent. @damccorm could you take a look?

**Comment by damccorm** [comment]
Hey @mchenx - this looks like its probably an agent issue like Deepak said - would you mind opening an issue at https://github.com/microsoft/azure-pipelines-agent? That is probably the best place to get the right eyes on it, this repo is meant for issues/code specifically related to tasks.

**Comment by mchenx** [comment]
sure, thanks for looking at this

**Comment by mchenx** [comment]
I have opened one  [https://github.com/microsoft/azure-pipelines-agent/issues/3110](url)
but no one looked into it, it's been a week

**Comment by ammohant** [comment]
Hey @mchenx   - Can you put the ask against  https://github.com/microsoft/azure-pipelines-agent/issues/3110 given that it is likely to be an agent specific issue  ?

**Comment by mchenx** [comment]
ok, maybe I can find a new centos vm when I have sometime and setup it from scratch to see if the issue goes away...
