### ISSUE TITLE
JenkinsDownloadArtifacts task fails with "Cannot find module 'underscore'"

### ISSUE THREAD

**Issue by TudorDarian** [microsoft/azure-pipelines-tasks#17029]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: JenkinsDownloadArtifacts

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: private

- Agent - Hosted or Private: 

    - If using private agent, provide the OS of the machine running the agent and the agent version: agent OS: Windows Server 2019, agent version: 2.211.0

## Issue Description

JenkinsDownloadArtifacts started failing with 'Cannot find module 'underscore'' with version 1.211.0. Currently downgraded to using version 1.208.0 as a workaround.

### Task logs

[JenkinsDownloadArtifact_log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/9762712/JenkinsDownloadArtifact_log.txt)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting
- Enabled debug logs on the pipeline

### Error logs
(Duplicate of task logs)
[JenkinsDownloadArtifact_log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/9762712/JenkinsDownloadArtifact_log.txt)

**Comment by GunnyDev** [comment]
We are also facing this issue this Morning using 1.211.0, worked fine in 1.208.0 looks like #16907 is the culprit @PavloAndriiesh

**Comment by TudorDarian** [comment]
I would have thought this is the PR that cause it: [#16910](https://github.com/microsoft/azure-pipelines-tasks/pull/16910)

**Comment by GunnyDev** [comment]
Yes you are correct, seems I picked the wrong one, updated.

**Comment by tfabraham** [comment]
This has broken numerous releases for us, completely by surprise after automatic agent updates. We have too many agents to manually roll them all back.

**Comment by mmrazik** [comment]
Sorry for the breakage. We are in the process of rolling back the change.

**Comment by GunnyDev** [comment]
Any updates on this, it's been 2 Days since we have been unable to run any releases. We are unable to do a work around as the release is a large process created a long time ago. It will take significant effort to move it all to yaml pipelines where we can specify the exact version.
